language: node_js 
node_js:
 - node
 - lts/*

sudo: false
cache:
  directories:
  - node_modules

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all

before_install:
  - uname -a
  - lsb_release -a
install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: always
