language: python
dist: bionic
python: '3.8'
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - python -m pip install --upgrade pip pipenv
  - python -m pipenv install --dev --deploy
  - pip --version
  - tox --version
script:
  - python -m pipenv run tox -v
after_success:
  - python -m pipenv run tox -e coverage-report
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
