# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# https://discuss.circleci.com/t/multi-stage-docker/12386/4
version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout

      # When the provided docker version contains multistage docker support
      # These stanzas and and `machine: true` may be removed.
      - run: docker version
      - run:
          name: Disable host docker
          command: |
            sudo service docker stop
      - run:
          name: Install latest docker
          command: |
            curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version

      - run:
          name: Install additional python versions
          command: |
            pyenv install 2.7.13
            pyenv install 3.6.1

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/docker.tar
      - run:
          name: Load docker image layer cache
          command: |
            docker load -i ~/caches/docker.tar || true

      - run:
          name: Build docker image
          command: |
            docker build --cache-from=bencord0/blog -t bencord0/blog .

      # The tests!
      - run:
          name: Python2.7 tests
          command: |
            pyenv local 2.7.13
            pip install -r test-requirements.txt
            tox
          environment:
            TOXENV: py27

      - run:
          name: Python3.6 tests
          command: |
            pyenv local 3.6.1
            pip install -r test-requirements.txt
            tox
          environment:
            TOXENV: py36

      - run:
          name: lint
          command: tox
          environment:
            TOXENV: flake8

      - run:
          name: coverage
          command: tox
          environment:
            TOXENV: coverage-report

      - run:
          name: Save docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/docker.tar bencord0/blog
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/docker.tar
