# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# https://discuss.circleci.com/t/multi-stage-docker/12386/4
version: 2.1
jobs:
  build:

    docker:
      - image: circleci/python:3.9

    working_directory: ~/app
    steps:
      - checkout

      # Remove this stanza when the default version of docker supports multi-stage builds
      - setup_remote_docker:
          version: 19.03.12

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/docker.tar
      - run:
          name: Load docker image layer cache
          command: |
            docker load -i ~/caches/docker.tar || true

      - run:
          name: Build docker image
          command: |
            docker build --cache-from=bencord0/blog -t bencord0/blog .

      # The tests!
      - run: echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV

      - run:
          name: tests
          command: |
            pipenv install --dev --deploy
            pipenv run tox
          environment:
            TOXENV: py38

      - run:
          name: lint
          command: pipenv run tox
          environment:
            TOXENV: flake8

      - run:
          name: coverage
          command: pipenv run tox
          environment:
            TOXENV: coverage-report

      - run:
          name: Save docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/docker.tar bencord0/blog
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/docker.tar
